### ISSUE TITLE
Some Error 

### ISSUE THREAD

**Issue by MyPushpendra** [xpeedstudio/wp-fundraising#10]
1) We Can't Add or Rename "INVEST NOW" Button.... So Please Add This Features anyone can Add Custom Name For this Button

2.) You give features to add video but this is not working so please solve this .... when we are adding video this is not displaying in front end.....

3.) Check this CrowdFunding Plugin and Add Additional Display Themes Like This

**Comment by xperter** [comment]
1. 'wf_single_invest_now_button_text' : this is the filter to change INVEST NOW button text. You can check documentation.

2. video feature is fixed in updated version
