### ISSUE TITLE
Products WP Fundraising no end date

### ISSUE THREAD

**Issue by ORdinarycas** [xpeedstudio/wp-fundraising#27]
Create campaign for crowdfunding

WP Fundraising uses the power of WooCommerce. You just need to create a product selecting WP Fundraising as product data. See image bellow.

http://xpeedstudio.net/documentation/wp-fundraising/#BackorDonateCampaign

http://xpeedstudio.net/documentation/wp-fundraising/images/wf_crowdfunding_1.png

I can not find End date input

**Comment by Ataurr** [comment]
Hi

We are upgrading this plugin in a new way. 

This will be ready within these months.

**Comment by Ataurr** [comment]
https://wordpress.org/plugins/wp-fundraising-donation/
